"""
Graph-based GROMACS topology generation for lignin chains.

The topology is built straight from the atomistic chain topology produced by
:class:`lignoforge.structure.generator.MolecularStructureGenerator` (atoms,
covalent bonds and the linkage type of every inter-monomer bond).  Unlike the
``pdb2gmx`` route, it makes no assumption about residue order or adjacency, so
it is valid for linear, branched and ring-closed (β-5, β-β) chains.

Angles, proper dihedrals, 1-4 pairs and aromatic impropers are all derived
from the bond graph.  Bonded parameters are deliberately left blank in the
``.top`` file so that ``grompp`` resolves them from ``oplsaa.ff/ffbonded.itp``;
a missing parameter therefore surfaces as an explicit grompp error rather
than being silently dropped.
"""

from __future__ import annotations

import collections
import json
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Set, Tuple

from lignoforge.forcefield.charges import neutralize_residue
from lignoforge.forcefield.opls import (
    EXTRA_DIHEDRALTYPES,
    TypingError,
    linkage_position,
    type_residue,
)

__all__ = ["Atom", "ChainTopology", "build_chain_topology", "write_gromacs_system"]

_RING_NAMES = ("C1", "C2", "C3", "C4", "C5", "C6")
_IMPROPER_MACRO = "improper_Z_CA_X_Y"
_FF_INCLUDE = "oplsaa.ff/forcefield.itp"

_EM_MDP = """\
; Energy minimisation of a single lignin chain (generated by LignoForge)
integrator      = steep
emtol           = 500.0
emstep          = 0.001
nsteps          = 10000
cutoff-scheme   = Verlet
nstlist         = 10
pbc             = xyz
coulombtype     = PME
rcoulomb        = 1.0
rvdw            = 1.0
constraints     = none
"""


@dataclass
class Atom:
    index: int            # 1-based, contiguous, residue-major
    name: str
    element: str
    resid: int            # 1-based residue number
    resname: str
    opls: str
    charge: float
    xyz: Tuple[float, float, float]  # Å


@dataclass
class ChainTopology:
    """Typed, fully connected description of one lignin chain."""

    name: str
    atoms: List[Atom]
    bonds: List[Tuple[int, int]]
    angles: List[Tuple[int, int, int]]
    dihedrals: List[Tuple[int, int, int, int]]
    pairs: List[Tuple[int, int]]
    impropers: List[Tuple[int, int, int, int]]
    linkages: List[dict] = field(default_factory=list)
    charge_report: List[dict] = field(default_factory=list)

    @property
    def net_charge(self) -> float:
        return round(sum(a.charge for a in self.atoms), 6)

    # ── Writers ───────────────────────────────────────────────────────────────

    def write_top(
        self,
        path: str,
        forcefield_include: str = _FF_INCLUDE,
        extra_includes: Sequence[str] = (),
    ) -> str:
        """
        Write a self-contained GROMACS ``.top`` (single molecule).

        ``extra_includes`` are emitted after the molecule definition and
        before ``[ system ]`` (e.g. ``oplsaa.ff/tip3p.itp`` for solvation).
        """
        L: List[str] = [
            "; GROMACS topology generated by LignoForge (graph-based, OPLS-AA)",
            f"; atoms={len(self.atoms)} bonds={len(self.bonds)} "
            f"angles={len(self.angles)} dihedrals={len(self.dihedrals)} "
            f"pairs={len(self.pairs)} impropers={len(self.impropers)}",
            f"; net charge = {self.net_charge:+.4f} e",
            "",
            f'#include "{forcefield_include}"',
            "",
            "; Torsions missing from OPLS-AA but needed for lignin side chains",
            EXTRA_DIHEDRALTYPES,
            "[ moleculetype ]",
            "; name  nrexcl",
            f"{self.name}  3",
            "",
            "[ atoms ]",
            ";   nr  type     resnr residue  atom   cgnr   charge",
        ]
        for a in self.atoms:
            L.append(
                f"{a.index:6d}  {a.opls:<9s}{a.resid:5d}  {a.resname:<6s} "
                f"{a.name:<5s}{a.index:6d} {a.charge:9.4f}"
            )
        L += ["", "[ bonds ]", ";  ai   aj funct"]
        L += [f"{i:6d}{j:6d}     1" for i, j in self.bonds]
        L += ["", "[ pairs ]", ";  ai   aj funct"]
        L += [f"{i:6d}{j:6d}     1" for i, j in self.pairs]
        L += ["", "[ angles ]", ";  ai   aj   ak funct"]
        L += [f"{i:6d}{j:6d}{k:6d}     1" for i, j, k in self.angles]
        L += ["", "[ dihedrals ]", "; proper (Ryckaert-Bellemans)",
              ";  ai   aj   ak   al funct"]
        L += [f"{i:6d}{j:6d}{k:6d}{l:6d}     3" for i, j, k, l in self.dihedrals]
        L += ["", "[ dihedrals ]", "; improper (aromatic planarity)",
              ";  ai   aj   ak   al funct  macro"]
        L += [f"{i:6d}{j:6d}{k:6d}{l:6d}     1  {_IMPROPER_MACRO}"
              for i, j, k, l in self.impropers]
        for inc in extra_includes:
            L += ["", f'#include "{inc}"']
        L += ["", "[ system ]", self.name, "", "[ molecules ]",
              f"{self.name}  1", ""]
        _write(path, "\n".join(L))
        return path

    def write_gro(self, path: str, margin_nm: float = 1.5) -> str:
        """Write a ``.gro`` file with the chain centred in a cubic box."""
        xs = [a.xyz[0] for a in self.atoms]
        ys = [a.xyz[1] for a in self.atoms]
        zs = [a.xyz[2] for a in self.atoms]
        centre = [(max(v) + min(v)) / 2 for v in (xs, ys, zs)]
        extent = max(max(v) - min(v) for v in (xs, ys, zs)) / 10.0
        box = extent + 2 * margin_nm
        L = [self.name, f"{len(self.atoms):5d}"]
        for a in self.atoms:
            x, y, z = (
                (a.xyz[d] - centre[d]) / 10.0 + box / 2 for d in range(3)
            )
            L.append(
                f"{a.resid % 100000:5d}{a.resname:<5s}{a.name:>5s}"
                f"{a.index % 100000:5d}{x:8.3f}{y:8.3f}{z:8.3f}"
            )
        L.append(f"{box:10.5f}{box:10.5f}{box:10.5f}")
        _write(path, "\n".join(L))
        return path


def _write(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w") as fh:
        fh.write(text if text.endswith("\n") else text + "\n")


# ── Graph helpers ─────────────────────────────────────────────────────────────

def _shortest_paths(adj: Dict[int, Set[int]], source: int, max_depth: int) -> Dict[int, int]:
    dist = {source: 0}
    queue = collections.deque([source])
    while queue:
        u = queue.popleft()
        if dist[u] == max_depth:
            continue
        for v in adj[u]:
            if v not in dist:
                dist[v] = dist[u] + 1
                queue.append(v)
    return dist


def _derive_bonded_terms(adj: Dict[int, Set[int]], bonds: List[Tuple[int, int]]):
    angles = [
        (i, j, k)
        for j in sorted(adj)
        for i, k in _combinations(sorted(adj[j]))
    ]
    dihedrals = []
    for j, k in bonds:
        for i in sorted(adj[j] - {k}):
            for l in sorted(adj[k] - {j}):
                if i != l and l not in adj[i]:
                    dihedrals.append((i, j, k, l))
    pairs = []
    for i in sorted(adj):
        for l, d in _shortest_paths(adj, i, 3).items():
            if d == 3 and i < l:
                pairs.append((i, l))
    return angles, dihedrals, pairs


def _combinations(items: List[int]):
    for a in range(len(items)):
        for b in range(a + 1, len(items)):
            yield items[a], items[b]


# ── Public builder ────────────────────────────────────────────────────────────

def build_chain_topology(chain: dict, name: Optional[str] = None) -> ChainTopology:
    """
    Build a typed :class:`ChainTopology` from an atomistic chain topology dict
    (schema ``lignoforge-atomistic-topology-v1``).

    Raises
    ------
    lignoforge.forcefield.opls.TypingError
        If a bond or atom cannot be mapped onto the supported linkage /
        atom-type tables.
    """
    name = name or f"LIG{chain.get('chain_id', 'A')}"

    # ── Atoms in residue-major order ──────────────────────────────────────────
    raw = sorted(
        (a for m in chain["monomers"] for a in m["atoms"]),
        key=lambda a: (int(a["monomer_id"]), int(a["atom_id"])),
    )
    new_index = {int(a["atom_id"]): i + 1 for i, a in enumerate(raw)}
    resid_of = {m_id: r + 1 for r, m_id in enumerate(
        sorted({int(a["monomer_id"]) for a in raw}))}
    res_atoms: Dict[int, Dict[str, dict]] = collections.defaultdict(dict)
    for a in raw:
        res_atoms[int(a["monomer_id"])][a["atom_name"]] = a
    by_id = {int(a["atom_id"]): a for a in raw}

    # ── Bonds and linkage context ─────────────────────────────────────────────
    bonds: Set[Tuple[int, int]] = set()
    context: Dict[int, Dict[str, Tuple[str, str]]] = collections.defaultdict(dict)
    linkages: List[dict] = []
    for b in chain["bonds"]:
        a1, a2 = int(b["atom1_id"]), int(b["atom2_id"])
        i, j = sorted((new_index[a1], new_index[a2]))
        bonds.add((i, j))
        if b.get("scope") != "inter_monomer":
            continue
        lname = b.get("linkage_type")
        n1, n2 = by_id[a1]["atom_name"], by_id[a2]["atom_name"]
        m1, m2 = int(b["monomer1_id"]), int(b["monomer2_id"])
        for m, n, partner in ((m1, n1, n2), (m2, n2, n1)):
            pos = linkage_position(lname, n, partner)
            if n in context[m] and context[m][n] != (lname, pos):
                raise TypingError(
                    f"Atom {n} of residue {resid_of[m]} is in two different "
                    f"linkage roles: {context[m][n]} and {(lname, pos)}"
                )
            context[m][n] = (lname, pos)
        linkages.append({
            "linkage": lname,
            "residue_1": resid_of[m1], "atom_1": n1,
            "residue_2": resid_of[m2], "atom_2": n2,
        })
    bond_list = sorted(bonds)

    # ── Typing and per-residue neutralisation ─────────────────────────────────
    atoms: Dict[int, Atom] = {}
    report: List[dict] = []
    for m_id in sorted(res_atoms):
        names = set(res_atoms[m_id])
        typed = type_residue(names, context[m_id])
        charges, residual, shift = neutralize_residue(
            {n: q for n, (_t, q) in typed.items()})
        resname = next(iter(res_atoms[m_id].values()))["residue_name"]
        report.append({
            "residue": resid_of[m_id], "resname": resname,
            "linkages": sorted({lk for lk, _ in context[m_id].values()}),
            "raw_net_charge": round(residual, 4),
            "max_atom_shift": round(shift, 4),
        })
        for n, a in res_atoms[m_id].items():
            idx = new_index[int(a["atom_id"])]
            atoms[idx] = Atom(
                index=idx, name=n, element=a["element"],
                resid=resid_of[m_id], resname=resname,
                opls=typed[n][0], charge=charges[n],
                xyz=(float(a["x"]), float(a["y"]), float(a["z"])),
            )

    adj: Dict[int, Set[int]] = {i: set() for i in atoms}
    for i, j in bond_list:
        adj[i].add(j)
        adj[j].add(i)

    angles, dihedrals, pairs = _derive_bonded_terms(adj, bond_list)

    # ── Aromatic impropers (graph-derived, valid for any substituent) ─────────
    impropers: List[Tuple[int, int, int, int]] = []
    ring_index: Dict[Tuple[int, str], int] = {
        (a.resid, a.name): a.index for a in atoms.values()
        if a.name in _RING_NAMES and a.element == "C"
    }
    for (resid, cname), centre in sorted(ring_index.items(), key=lambda t: t[1]):
        k = int(cname[1])
        prev = ring_index[(resid, f"C{(k - 2) % 6 + 1}")]
        nxt = ring_index[(resid, f"C{k % 6 + 1}")]
        subst = adj[centre] - {prev, nxt}
        if len(subst) != 1:
            raise TypingError(
                f"Ring atom {cname} of residue {resid} has {len(subst)} "
                f"non-ring neighbours (expected 1)"
            )
        impropers.append((prev, nxt, centre, next(iter(subst))))

    topo = ChainTopology(
        name=name,
        atoms=[atoms[i] for i in sorted(atoms)],
        bonds=bond_list, angles=angles, dihedrals=dihedrals,
        pairs=pairs, impropers=impropers,
        linkages=linkages, charge_report=report,
    )
    if abs(topo.net_charge) > 1e-6:
        raise TypingError(f"Net charge {topo.net_charge} after neutralisation")
    return topo


def write_gromacs_system(
    chain: dict,
    output_dir: str,
    name: str = "lignin",
) -> Dict[str, str]:
    """
    Build and write a complete, ready-to-minimise GROMACS input set.

    Files written to *output_dir*: ``<name>.top``, ``<name>.gro``, ``em.mdp``
    and ``<name>_topology_report.json``.  Run, e.g.::

        gmx grompp -f em.mdp -c <name>.gro -p <name>.top -o em.tpr
    """
    topo = build_chain_topology(chain, name=name)
    paths = {
        "top": topo.write_top(os.path.join(output_dir, f"{name}.top")),
        "gro": topo.write_gro(os.path.join(output_dir, f"{name}.gro")),
    }
    mdp = os.path.join(output_dir, "em.mdp")
    _write(mdp, _EM_MDP)
    paths["mdp"] = mdp
    rep = os.path.join(output_dir, f"{name}_topology_report.json")
    with open(rep, "w") as fh:
        json.dump({
            "name": name, "n_atoms": len(topo.atoms),
            "net_charge": topo.net_charge,
            "linkages": topo.linkages, "residues": topo.charge_report,
        }, fh, indent=2)
    paths["report"] = rep
    return paths
