"""
GROMACS ``.mdp`` templates for the lignin simulation workflow.

Every template is plain text with explicit values so that the generated
files can be read, edited and reused outside LignoForge.
"""

from __future__ import annotations

__all__ = ["em_mdp", "nvt_mdp", "npt_mdp", "prod_mdp", "DT_PS"]

DT_PS = 0.002   # 2 fs with h-bond constraints

_COMMON_NB = """\
cutoff-scheme       = Verlet
nstlist             = 20
rcoulomb            = 1.0
rvdw                = 1.0
coulombtype         = PME
fourierspacing      = 0.12
pme-order           = 4
DispCorr            = EnerPres
pbc                 = xyz
"""


def _steps(time_ps: float) -> int:
    return max(1, int(round(time_ps / DT_PS)))


def em_mdp(emtol: float = 500.0, nsteps: int = 20000) -> str:
    return f"""\
; Energy minimisation (generated by LignoForge)
integrator          = steep
emtol               = {emtol}
emstep              = 0.001
nsteps              = {nsteps}
constraints         = none
{_COMMON_NB}"""


def _dynamics(time_ps, temperature, label, pcoupl, gen_vel, continuation, out_ps):
    pc = (
        f"""pcoupl              = {pcoupl}
pcoupltype          = isotropic
tau-p               = 2.0
ref-p               = 1.0
compressibility     = 4.5e-5
refcoord-scaling    = com
"""
        if pcoupl != "no" else "pcoupl              = no\n"
    )
    return f"""\
; {label} (generated by LignoForge)
integrator          = md
dt                  = {DT_PS}
nsteps              = {_steps(time_ps)}
nstxout-compressed  = {max(1, int(out_ps / DT_PS))}
nstenergy           = {max(1, int(out_ps / DT_PS))}
nstlog              = {max(1, int(out_ps / DT_PS))}
continuation        = {"yes" if continuation else "no"}
constraint-algorithm = lincs
constraints         = h-bonds
lincs-iter          = 1
lincs-order         = 4
tcoupl              = v-rescale
tc-grps             = System
tau-t               = 0.1
ref-t               = {temperature}
{pc}gen-vel             = {"yes" if gen_vel else "no"}
gen-temp            = {temperature}
gen-seed            = -1
{_COMMON_NB}"""


def nvt_mdp(time_ps: float = 100.0, temperature: float = 300.0) -> str:
    return _dynamics(time_ps, temperature, "NVT equilibration", "no", True, False, 10.0)


def npt_mdp(time_ps: float = 200.0, temperature: float = 300.0) -> str:
    return _dynamics(time_ps, temperature, "NPT equilibration", "C-rescale", False, True, 10.0)


def prod_mdp(time_ps: float = 10000.0, temperature: float = 300.0, npt: bool = True) -> str:
    return _dynamics(
        time_ps, temperature, "Production", "Parrinello-Rahman" if npt else "no",
        False, True, 10.0,
    )
