/** Short descriptions of the OPLS-AA types LignoForge assigns (see docs: OPLS-AA parametrisation). */
export const OPLS_INFO: Record<string, string> = {
  opls_136: "sp³ CH₂ (carbon neighbours only)",
  opls_137: "sp³ CH (carbon neighbours only)",
  opls_140: "H on sp³ alkyl C",
  opls_142: "sp² vinyl C (Cα=Cβ)",
  opls_144: "vinyl H",
  opls_145: "aromatic C–H",
  opls_146: "aromatic H",
  opls_154: "alcohol O",
  opls_155: "alcohol H",
  opls_156: "H on C–OH / C–O carbon",
  opls_157: "CH₂–OH carbon (Cγ)",
  opls_166: "phenol ring C–OH",
  opls_167: "phenol O",
  opls_168: "phenol H",
  opls_179: "aryl-ether / methoxy O",
  opls_181: "methoxy CH₃ carbon",
  opls_183: "sp³ ether carbon (Cα/Cβ–O–Ar)",
  opls_185: "H on ether/methoxy carbon",
  opls_199: "ring C bearing O (anisole-type)",
  opls_219: "benzylic alcohol carbon (Cα–OH)",
  opls_221: "ipso ring C (substituted, no H)",
};
